theme = "base16_default"

[editor]
line-number = "relative"
mouse = false
true-color = true
color-modes = true
auto-save = true
bufferline = "always"
cursorcolumn = true

[editor.statusline]
center = ["version-control"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
snippets = true

[keys.normal]
D= "kill_to_line_end"
